// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"logo-1","Show Custom Splash":"true","Custom Image":"logo-3","Fade Out Time":"60","Fade In Time":"60","Wait Time":"160"}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"Something","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}},
{"name":"EnemyBook","status":true,"description":"Displays detailed statuses of enemies.","parameters":{"Unknown Data":"Proably some idiot"}},
{"name":"SRD_SkipTitleWithoutSave","status":false,"description":"This Plugin skips the title screen if there is no save file present.","parameters":{}},
{"name":"SRD_AutoUpdater","status":false,"description":"Allows developers to set up automatic updates to occur whenever a player plays the game.","parameters":{"Update Text URL":"","Initial Version":"0.90","== Version Options ==":"","Draw Version":"true","Version Format":"v%1","Version Text X":"Graphics.boxWidth - textWidth - 8","Version Text Y":"Graphics.boxHeight - textHeight - 24","Version Text Font":"GameFont","Version Text Color":"#FFFFFF","Version Text Size":"28","Version Outline Size":"3","Version Italic":"true"}}
];
